-- MySQL Script generated by MySQL Workbench
-- Wed Jan 25 08:04:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rental
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rental` DEFAULT CHARACTER SET utf8 ;
USE `rental` ;

-- -----------------------------------------------------
-- Table `rental`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rental`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Imie` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `is_admin?` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rental`.`Film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rental`.`Film` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rental`.`User_has_Film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rental`.`User_has_Film` (
  `User_id` INT NOT NULL,
  `Film_id` INT NOT NULL,
  PRIMARY KEY (`User_id`, `Film_id`),
  CONSTRAINT `fk_User_has_Film_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `rental`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Film_Film1`
    FOREIGN KEY (`Film_id`)
    REFERENCES `rental`.`Film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
